Hyperparameters:
  epochs: 10
  use_gpu: false
Dataset:
  path_to_data: 'hatefulmemes/'
  cache_size: 1000
  batch_size: 32
  shuffle: true
Models:
  base_import_package: 'transformers'
  image_processor_package: 'ViTImageProcessor'
  image_model_package: 'ViTModel'
  text_tokenizer_package: 'BartTokenizer'
  text_model_package: 'BartModel'
  image_processor_pretrained: 'google/vit-base-patch16-224-in21k'
  image_model_name: 'google/vit-base-patch16-224'
  text_processor_pretrained: 'facebook/bart-large'
  text_model_name: 'facebook/bart-large'
  encoder_finetuning: True
  regularization: False
  mlp_num_classes: 2
  mlp_hidden_sizes:
    - 128
    - 64
  mlp_dropout_prob:
    - 0.5
    - 0.7
Optimizers:
  optimizer: 'Adam'
  learning_rate: 0.01
  use_lr_scheduler: false
  lr_scheduler: ''
  momentum: 0.9
Loss:
  loss_fn: 'BCELoss'
  use_custom_loss: false
  custom_loss_fn: ''
  reg_lambda: 0.01
Save Best:
  save_best_models: false
  save_best_weights: false